version: '3.9'

services:
  django-app:
    image: nginx-uwsgi-django
    restart: always
    container_name: django
    command: bash -c "service nginx start && uwsgi --ini /etc/uwsgi/django.ini && tail -f /dev/null"
    ports:
      - '8000:8000'
    working_dir: /E-Commerce-Backend-Django
    volumes:
      - .:/E-Commerce-Backend-Django
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: db_pass
      MYSQL_DB: EComLocal

  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: db_pass
      MYSQL_DATABASE: EComLocal

volumes:
  mysql-data: