# Generated by Django 3.2 on 2022-09-05 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20220905_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='shop.sport'),
        ),
    ]
