# Generated by Django 3.2 on 2022-09-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20220905_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='link',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
