# Generated by Django 3.2 on 2022-09-06 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_message_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='nav_image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='sport',
            name='nav_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
