# Generated by Django 3.2 on 2022-11-03 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'children': None}, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
