# Generated by Django 3.2 on 2022-12-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_featuredimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredimage',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'parent': None}, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
