# Generated by Django 3.2 on 2022-12-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20221217_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredimage',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
